version: "3.3"
services:
  blue:
    image: duhanmo/dev-otte-api:latest
    container_name: blue
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /root/secret:/root/app/secret
    environment:
      TZ: "Asia/Seoul"
  green:
    image: duhanmo/dev-otte-api:latest
    container_name: green
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /root/secret:/root/app/secret
    environment:
      TZ: "Asia/Seoul"