version: "3.8"
services:
  db:
    image: mysql:8
    container_name: lostark
    restart: always
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lostark
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
