name: Main branch CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4

    -
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"

    -
      name: Setup Gradle and caching
      uses: gradle/gradle-build-action@v2

    -
      name: Gradle build
      run: |
        ./gradlew clean build

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        file: Product.Dockerfile
        context: .
        push: true
        tags: duhanmo/product-otte-api:latest
    -
      name: Create secret to file into runner server
      run: echo "${{ secrets.APPLICATION_PRODUCT_PROPERTIES }}" > ./application-product.properties

    -
      name: Send properties file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_PRODUCT }}
        username: ${{ secrets.SSH_USERNAME_PRODUCT }}
        # NCP는 password로 접속
        password: ${{ secrets.SSH_PASSWORD_PRODUCT }}
        port: ${{ secrets.SSH_PORT_PRODUCT }}
        # 깃허브 러너 환경에 존재하는 파일
        source: "./application-product.properties"
        # 서버 내부 해당 디렉터리가 존재해야함
        target: "/root/secret"

    -
      name: Send docker-compose.api.product.yml to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_PRODUCT }}
        username: ${{ secrets.SSH_USERNAME_PRODUCT }}
        password: ${{ secrets.SSH_PASSWORD_PRODUCT }}
        port: ${{ secrets.SSH_PORT_PRODUCT }}
        source: "./docker/docker-compose.api.product.yml"
        target: "/root"
    -
      name: Send deploy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST_PRODUCT }}
        username: ${{ secrets.SSH_USERNAME_PRODUCT }}
        password: ${{ secrets.SSH_PASSWORD_PRODUCT }}
        port: ${{ secrets.SSH_PORT_PRODUCT }}
        source: "./script/deploy-product.sh"
        target: "/root"

    -
      name: Execute docker pull and deploy-product.sh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST_PRODUCT }}
        username: ${{ secrets.SSH_USERNAME_PRODUCT }}
        password: ${{ secrets.SSH_PASSWORD_PRODUCT }}
        port: ${{ secrets.SSH_PORT_PRODUCT }}
        script: |
          sudo docker pull duhanmo/product-otte-api:latest
          chmod 777 /root/script/deploy-product.sh
          /root/script/deploy-product.sh
          docker image prune -f